{
  "LOW_STATE": "rt/lf/lowstate",
  "MULTIPLE_STATE": "rt/multiplestate",
  "FRONT_PHOTO_REQ": "rt/api/front_videohub/request",
  "BACK_PHOTO_REQ": "rt/api/back_videohub/request",
  "G1_FRONT_PHOTO_REQ": "rt/api/videohub/request",
  "FRONT_VIDEO_HUB": "rt/front_videohub/videostream",
  "BACK_VIDEO_HUB": "rt/back_videohub/videostream",
  "NORMAL_FRONT_VIDEO_HUB": "rt/frontvideostream",
  "ULIDAR": "rt/utlidar/voxel_map",
  "ULIDAR_ARRAY": "rt/utlidar/voxel_map_compressed",
  "ULIDAR_STATE": "rt/utlidar/lidar_state",
  "ROBOTODOM": "rt/utlidar/robot_pose",
  "UWB_REQ": "rt/api/uwbswitch/request",
  "UWB_STATE": "rt/uwbstate",
  "LOW_CMD": "rt/lowcmd",
  "WIRELESS_CONTROLLER": "rt/wirelesscontroller",
  "SPORT_MOD": "rt/api/sport/request",
  "CONFIG": "rt/api/config/request",
  "G1_ARM_SPORT_MOD": "rt/api/arm/request",
  "SPORT_MOD_STATE": "rt/sportmodestate",
  "LF_SPORT_MOD_STATE": "rt/lf/sportmodestate",
  "BASH_REQ": "rt/api/bashrunner/request",
  "SELF_TEST": "rt/selftest",
  "GRID_MAP": "rt/mapping/grid_map",
  "SERVICE_STATE": "rt/servicestate",
  "GPT_FEEDBACK": "rt/gptflowfeedback",
  "VUI": "rt/api/vui/request",
  "OBSTACLES_AVOID": "rt/api/obstacles_avoid/request",
  "SLAM_QT_COMMAND": "rt/qt_command",
  "SLAM_ADD_NODE": "rt/qt_add_node",
  "SLAM_ADD_EDGE": "rt/qt_add_edge",
  "SLAM_QUERY_ALL_NODE": "rt/query_result_node",
  "SLAM_QUERY_ALL_EDGE": "rt/query_result_edge",
  "SLAM_QT_NOTICE": "rt/qt_notice",
  "SLAM_PC_TO_IMAGE_LOCAL": "rt/pctoimage_local",
  "SLAM_BUILD_MAP_ODOMETRY": "rt/lio_sam_ros2/mapping/odometry",
  "SLAM_RELOCATION_ODOMETRY": "rt/lio_sam_ros2/mapping/re_location_odometry",
  "G1_DEX3_LEFT_STATE": "rt/lf/dex3/left/state",
  "G1_DEX3_RIGHT_STATE": "rt/lf/dex3/right/state",
  "MAIN_BOARD_STATE": "rt/lf/mainboardstate",
  "BMS_STATE": "rt/lf/bmsstate",
  "DOUBLE_IMU": "rt/lf/lowstate_doubleimu",
  "SECONDARY_IMU_LF": "rt/lf/secondary_imu",
  "SECONDARY_IMU": "rt/secondary_imu",
  "LOG_SYSTEM_OUTBOUND": "rt/log_system_outbound",
  "G1_ARM_ACTION_STATE": "rt/arm/action/state",
  "SLAM_OPERATE_REQUEST": "rt/api/slam_operate/request",
  "SLAM_MAPPING_POINTS": "rt/unitree/slam_mapping/points",
  "SLAM_MAPPING_ODOM": "rt/unitree/slam_mapping/odom",
  "SLAM_RELOCATION_POINTS": "rt/unitree/slam_relocation/points",
  "SLAM_RELOCATION_ODOM": "rt/unitree/slam_relocation/odom",
  "SLAM_INFO": "rt/slam_info"
}

{
  "G1UpperLimbs": {
    "shakeHands_1": 27,
    "highFive": 18,
    "hug": 19,
    "hightWave": 26,
    "lowWave": 25,
    "clamp": 17,
    "blowKiss": 12,
    "makeHeartBothHands": 20,
    "makeHeartSingleHands": 21,
    "ultramanRay": 24,
    "bothHandsUp": 15,
    "singleHandsUp": 23,
    "refuse": 22,
    "releaseArm": 99
  },
  "G1State": {
    "Damp": 1,
    "ZeroTorque": 0,
    "Preparation": 4,
    "Seating": 3,
    "Walk_G1": 500,
    "Squat_G1": 706,
    "SquatUp_G1": 706,
    "LieUp_G1": 702
  },
  "G1BalanceState": {
    "Step_G1": 1,
    "Stand_G1": 0
  }
}